#!/usr/bin/env python3
"""Fail when a lockfile pin no longer satisfies the requirement that declared it.

The lockfiles are generated by pip-compile from requirements.txt and
requirements-dev.txt, but Dependabot only ever edits the .txt files: its
pip-compile support requires the generated file to be named *.txt before it
will look at it at all, and ours are named *.lock. So a bumped floor in a .txt
file leaves the corresponding .lock untouched, and nothing notices until an
unrelated pull request fails `pip-audit` for a package it never touched.

That is how cryptography stayed pinned at 49.0.0 under a `>=50.0.1` floor
while every open pull request failed the audit gate, and how mypy, pytest,
pylint, hypothesis, pip-tools and boto3 all drifted below their declared
floors at the same time.

Regenerating the locks and diffing would not catch this: pip-compile resolves
against the live index, so the output changes whenever anything upstream
publishes, and the check would fail for reasons that have nothing to do with
this repository. What is stable is the relationship the lockfile is supposed
to preserve: every pinned version satisfies the specifier that asked for it.
That is exactly what drifted, and it is decidable from the files alone.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version

ROOT = Path(__file__).resolve().parent.parent

# Each lockfile and the requirements file it is compiled from. A dev
# requirements file pulls in the runtime one with `-r`, and the constraints it
# inherits that way are followed rather than ignored.
PAIRS = [
    ("requirements.txt", "requirements.lock"),
    ("requirements-dev.txt", "requirements-dev.lock"),
]

# A pinned line in a hashed lockfile: `name==version \` before the hashes.
PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)")


def declared(path: Path, seen: set[Path] | None = None) -> dict[str, Requirement]:
    """The requirements a file declares, following `-r` includes."""
    seen = seen if seen is not None else set()
    resolved = path.resolve()
    if resolved in seen:
        return {}
    seen.add(resolved)

    out: dict[str, Requirement] = {}
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith(("-r ", "--requirement ")):
            out.update(declared(path.parent / line.split(None, 1)[1].strip(), seen))
            continue
        if line.startswith("-"):
            continue
        try:
            req = Requirement(line)
        except Exception:
            continue
        out[canonicalize_name(req.name)] = req
    return out


def pinned(path: Path) -> dict[str, str]:
    """The versions a hashed lockfile pins, by canonical name."""
    out: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        if raw[:1].isspace():
            continue
        match = PIN.match(raw.strip())
        if match:
            out[canonicalize_name(match.group(1))] = match.group(2)
    return out


def main() -> int:
    drifted: list[str] = []
    missing: list[str] = []

    for source_name, lock_name in PAIRS:
        source, lock = ROOT / source_name, ROOT / lock_name
        if not source.exists() or not lock.exists():
            print(f"missing {source_name} or {lock_name}", file=sys.stderr)
            return 2

        pins = pinned(lock)
        for name, req in declared(source).items():
            if not req.specifier:
                continue
            if name not in pins:
                missing.append(f"  {lock_name}: {req.name} is declared but not pinned")
                continue
            # prereleases=True so a pinned release candidate is judged against
            # the specifier rather than silently dropped from consideration.
            if not req.specifier.contains(Version(pins[name]), prereleases=True):
                drifted.append(
                    f"  {lock_name}: {req.name} pinned at {pins[name]}, "
                    f"but {source_name} declares {req.name}{req.specifier}"
                )

    if not drifted and not missing:
        print("lockfiles satisfy every declared requirement")
        return 0

    print("Lockfiles have drifted from the requirements that declare them.\n")
    for line in drifted + missing:
        print(line)
    print(
        "\nRegenerate them:\n"
        "  pip-compile --generate-hashes --output-file=requirements.lock requirements.txt\n"
        "  pip-compile --allow-unsafe --generate-hashes "
        "--output-file=requirements-dev.lock requirements-dev.txt\n"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
